### ISSUE TITLE
source文件内容

### ISSUE THREAD

**Issue by sheishixiaofu** [adamgallas/fpga_accelerator_yolov3tiny#1]
@@@source中acceltop文件和accel_conv关系能请作者指点一下吗？我尝试移植在PYNQ上，整个source放进去显示资源不够

**Comment by sheishixiaofu** [comment]
> 
请作者指点一下

**Comment by bald-prince** [comment]
请问下hls源码中的字库是怎么取的

**Comment by adamgallas** [comment]
该repo仅供学习参考，个人维护和答疑的精力有限，非常抱歉。
