### ISSUE TITLE
关于cal_addtree_int16_x9这个模块中的一些问题

### ISSUE THREAD

**Issue by out-of-order55** [adamgallas/fpga_accelerator_yolov3tiny#10]
assign a1_d1={a1[15],a1[15],a1[15:0]};
这一句代码中第18位为符号位吗,第17位又是什么?可以解答一下吗

**Comment by adamgallas** [comment]
这里是在做符号位扩展，把一个int16的数扩展到int18。也可以写成assign a1_d1={2{a1[15]},a1[15:0]}。
