### ISSUE TITLE
关于我调试该系统所遇到的问题

### ISSUE THREAD

**Issue by zhangxianbin1999** [adamgallas/fpga_accelerator_yolov3tiny#11]
以下是我调试时，出现的一些调试错误以及板子的连线图。

![IMG_20230415_160617](https://user-images.githubusercontent.com/104557952/232199741-f51a3c1c-872c-420f-8cbb-d4c151f6b97c.jpg)
![IMG_20230415_160802](https://user-images.githubusercontent.com/104557952/232199832-679fd340-aeec-40d2-869f-1d5b9477ac5d.jpg)
![IMG_20230415_160812](https://user-images.githubusercontent.com/104557952/232199939-c0b8651a-052c-4601-9514-14571ef6010f.jpg)

**Comment by adamgallas** [comment]
试试把摄像头连到左边的mipi口？看似是i2c配置摄像头出了问题

**Comment by zhangxianbin1999** [comment]
大佬，换了一个MIPI接口后，出现这样的问题，如何解决啊。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "adamgallas/fpga_accelerator_yolov3tiny"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月15日(星期六) 晚上9:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [adamgallas/fpga_accelerator_yolov3tiny] 关于我调试该系统所遇到的问题 (Issue #11)





 
试试把摄像头连到左边的mipi口？看似是i2c配置摄像头出了问题

**Comment by adamgallas** [comment]
emmm我没看到你的问题

**Comment by adamgallas** [comment]
如果没有其它问题我就close了？
