### ISSUE TITLE
关于我想学习您的代码并尝试移植到zedboard上的一些问题

### ISSUE THREAD

**Issue by Yuanzhe-hub** [adamgallas/fpga_accelerator_yolov3tiny#12]
您好，我在学习您的代码的过程中，发现您给神经网络的输入是418X258X8？yolov3 tiny的输入不是416X416X3吗？不知道我说的对不对。如果是对的，能告诉我为什么要修改输入的通道数吗？

**Comment by adamgallas** [comment]
你好。是的我给图像的输入是418*258，主要是第一次送进去算卷积的时候，是默认已经padding好的图像，上下左右各多了一个pixel
至于为什么是x8，是因为加速器是一个8x8的架构，一次性算8x8=64个3x3的卷积。但是第一层的通道数不足8，所以进行了补零。

**Comment by Yuanzhe-hub** [comment]
好的，谢谢。我还有一个问题，输入特征图数据在ddr中的存储顺序是按照通道存储的吗？比如：r1,g1,b1,r2,g2,b2......这样？

**Comment by adamgallas** [comment]
输入特征图数据在ddr中的存储是按照加速器的并行通道切分的，即 [C/8] x H x W x 8
