### ISSUE TITLE
zcu104移植问题

### ISSUE THREAD

**Issue by wgq18** [adamgallas/fpga_accelerator_yolov3tiny#14]
您好，我尝试将工程移植到zcu104上，对dout_0[0]的约束有疑问。您的约束是：
set_property PACKAGE_PIN B8 [get_ports {dout_0[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {dout_0[0]}]

请问B8引脚的作用是什么？zcu104上有相似功能的引脚吗？

谢谢您！

**Comment by adamgallas** [comment]
这个引脚是对mipi摄像机做开关的。你用不着的话可以把它删掉。我记得zcu104是没有mipi摄像机接口的，只有usb摄像机，这意味着mipi ip核，伽马矫正那一条摄像头支路你可以直接去掉了，换成你zcu104支持的摄像机。

**Comment by wgq18** [comment]
请问您的vitis版本是2021.1吗？我在2021.1版本中建立c工程编译，有大量重复定义的报错。
![Screenshot from 2023-05-25 17-51-23](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/58140458/6a925c10-9284-41e0-b9e2-69711dd2882a)
![Screenshot from 2023-05-25 17-52-21](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/58140458/ec751425-dab0-4c66-910c-909b31e4ebe3)
![Screenshot from 2023-05-25 17-52-03](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/58140458/19683c7a-0998-4593-ae1f-2bca9b7e4507)

**Comment by adamgallas** [comment]
我的版本是2019.2。移植的时候不应该直接改源工程，你应该自己新建一个platform，把代码拷过去。
________________________________
发件人: wgq18 ***@***.***>
发送时间: 2023年5月25日 17:57
收件人: adamgallas/fpga_accelerator_yolov3tiny ***@***.***>
抄送: Jindong Li ***@***.***>; Comment ***@***.***>
主题: Re: [adamgallas/fpga_accelerator_yolov3tiny] zcu104移植问题 (Issue #14)


请问您的vitis版本是2021.1吗？我在2021.1版本中建立c工程编译，有大量重复定义的报错。
[Screenshot from 2023-05-25 17-51-23]<https://user-images.githubusercontent.com/58140458/240876611-6a925c10-9284-41e0-b9e2-69711dd2882a.png>
[Screenshot from 2023-05-25 17-52-21]<https://user-images.githubusercontent.com/58140458/240876624-ec751425-dab0-4c66-910c-909b31e4ebe3.png>
[Screenshot from 2023-05-25 17-52-03]<https://user-images.githubusercontent.com/58140458/240876630-19683c7a-0998-4593-ae1f-2bca9b7e4507.png>

―

**Comment by YuHao-Chang** [comment]
@wgq18 請問您移植到zcu104使用的相機是哪一款?
最後移植是否成功?
