### ISSUE TITLE
关于在PS侧如何使用axi dma的问题？

### ISSUE THREAD

**Issue by Yuanzhe-hub** [adamgallas/fpga_accelerator_yolov3tiny#15]
您好，我在zedboard PL侧实现了一个LeNet神经网络，移植了您的AXI 接口的编写，并且使用了AXI DMA IP核。但是在PS侧，我不知道如何去使用AXI DMA，我移植了您的关于axi dma的部分代码，修改了中断号和地址。但是，我在下载验证时，PS侧接收不到PL侧的中断信号(ap_done)，不知道是什么原因。请问您当时是如何编写axi dma部分的？

**Comment by adamgallas** [comment]
axi dma的教程到处都有了，我建议你脱离这个工程先完成axi dma数据通路的验证，再去跑nn加速。
ap_done信号是自己在PL端定义的，我的定义方式和你的方式又可能不太一样，直接拿来用出问题的地方太多。
再加上。。axi dma在PL端出来的不需要驱动的axi stream，这个也不需要用到我的工程里的.v吧？自己根据axi stream的时序写逻辑就行。
