### ISSUE TITLE
B8,MIPI_A_PWUP_LS

### ISSUE THREAD

**Issue by DragMou1204** [adamgallas/fpga_accelerator_yolov3tiny#17]
你好，想请问vivado工程中的emio_gpio_o在io约束中绑定到了B8，手册上显示B8连接的是MIPI_A_PWUP_LS，MIPI_A_PWUP_LS这个引脚我在网上没查询到，请问有什么意义
![image](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/119485272/f55aef59-0106-4ef9-8afd-5ed3b0a1e3f7)

**Comment by adamgallas** [comment]
是power up的意思。是启动mipi摄像头的引脚

**Comment by DragMou1204** [comment]
我看我的板子的mipi例程没有这样引出，而且板子原理图中也没找到mipi_pwup相关引脚,那就不用引出启动了吧

**Comment by adamgallas** [comment]
那应该可以吧。我这个摄像头采集的环路是参考这个工程的：https://github.com/ATaylorCEngFIET/Genesys_ZU_MIPI_PCAM

**Comment by DragMou1204** [comment]
ok,感谢



在 2023-06-27 14:45:31，"Jindong Li" ***@***.***> 写道：

那应该可以吧。我这个摄像头采集的环路是参考这个工程的：https://github.com/ATaylorCEngFIET/Genesys_ZU_MIPI_PCAM
