### ISSUE TITLE
能否提供一下该卷积加速器的仿真测试文件，有偿

### ISSUE THREAD

**Issue by zhangxianbin1999** [adamgallas/fpga_accelerator_yolov3tiny#18]

**Comment by adamgallas** [comment]
由于工程本身也很大，写testbench的工程量甚至超过了写这个加速器本身，当时我验证的时候就是反复上板+ila抓数据来完成验证的。
但是该工程是两年前完成的了，当时习惯不太好，测试的工程过于凌乱，也没有很好地维护，所以这个repo目前只具备参考价值了。

**Comment by xyfgemini** [comment]
可否加好友


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Jindong Li ***@***.***>
发送时间: Wednesday, August 30, 2023 12:02:57 PM
收件人: adamgallas/fpga_accelerator_yolov3tiny ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [adamgallas/fpga_accelerator_yolov3tiny] 能否提供一下该卷积加速器的仿真测试文件，有偿 (Issue #18)


Closed #18<https://github.com/adamgallas/fpga_accelerator_yolov3tiny/issues/18> as completed.

―
