### ISSUE TITLE
Accel FM LEN的设置问题

### ISSUE THREAD

**Issue by lllkjh** [adamgallas/fpga_accelerator_yolov3tiny#19]
想请问下vitis prj里面accel_parameter.h中特征图的尺寸设置（代码93至107行）是怎么考量的呢，为什么行的base是8而列的base是13，还有就是为什么要+2呢

**Comment by adamgallas** [comment]
是因为416*256降采样了32倍得到8x13。+2是因为针对3x3卷积提前做了same padding
