### ISSUE TITLE
vivado工程遇到的问题

### ISSUE THREAD

**Issue by zhangxianbin1999** [adamgallas/fpga_accelerator_yolov3tiny#20]
![55e7af1296b6750691948a23fd70d4f](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/104557952/5f68b9cb-4d6d-4570-a0ac-5b8169f286d5)

**Comment by adamgallas** [comment]
这是因为你没有安装我所用的板子的board file。你可以google一下怎么安装
