### ISSUE TITLE
请问一下量化文件的部分参数是什么意思？

### ISSUE THREAD

**Issue by 1218liu** [adamgallas/fpga_accelerator_yolov3tiny#23]
请问一下我想量化为8bit，那么这两个参数ofmch_t和first_chr要填什么呀，不太理解这些参数都是什么意思，请问作者能解答一下吗，十分感谢
![U0CP~5WLL}( C0B6ABJO7 S](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/144978280/3d4a5bed-3731-4e23-b1c4-34d5513c68e9)

**Comment by adamgallas** [comment]
有一说一，我也忘了。。
