### ISSUE TITLE
请问python工程中如图2所示的int8量化后的模型是如何得到的？

### ISSUE THREAD

**Issue by 1218liu** [adamgallas/fpga_accelerator_yolov3tiny#26]
![TT69EFE27WX0N4(@0BQL`SH](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/144978280/2e28b024-9f17-49e9-880d-d246816d5aca)
![~XR398@8X7}2NVD%H6{EP$A](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/144978280/26d45206-6d80-43c7-a421-389cb4c04a13)

**Comment by adamgallas** [comment]
你可以再仔细看看python整个工程。另外，量化是个很成熟的技术，到处都有成熟的教程，pytorch也有成熟的api，这个工程只是个很粗糙的量化的小demo。你完完全全可以多了解一下量化的相关知识

**Comment by DragMou1204** [comment]
![image](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/119485272/81047463-ec89-4616-9945-5f7ec6aca7cc)

**Comment by 1218liu** [comment]
> ![image](https://user-images.githubusercontent.com/119485272/279309733-81047463-ec89-4616-9945-5f7ec6aca7cc.png)

请问·一下出现这个错误是怎么回事啊，你能方便解答一下吗
![Uploading ZZ`1G6T%UZ~NY{BG`ILD1RY.png…]()

**Comment by 1218liu** [comment]
![Uploading ZZ`1G6T%UZ~NY{BG`ILD1RY.png…]()

**Comment by 1218liu** [comment]
> ![image](https://user-images.githubusercontent.com/119485272/279309733-81047463-ec89-4616-9945-5f7ec6aca7cc.png)

请问一下能加一下您的联系方式吗？不知道如何生成量化后的pt模型，您方便解答一下吗？

**Comment by DragMou1204** [comment]
qq941079882
