### ISSUE TITLE
检测水果时出现问题

### ISSUE THREAD

**Issue by 1218liu** [adamgallas/fpga_accelerator_yolov3tiny#28]
复现您的源码后，将F开头的bin文件（口罩检测）改成自己生成的bin文件（也是F开头），头盔检测的bin文件没动，FCS.bin文件的标签种类为苹果，香蕉，橘子三种，可是始终识别不到橘子，在pycharm上跑推理的时候也能检测到橘子，可是上板子之后始终是将将橘子识别成苹果，请问一下作者能解答一下问题出在哪里吗？

![213e4408ae4a809d0d8a96f0c764923](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/144978280/4873f8ec-b987-47a9-a62a-ffb1d4dfdfb0)
![737511e166558ad7aa0c12ac4e06fe3](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/144978280/e9995de8-ec1e-4d38-b9d3-57a1a87cee16)
![a61bc3cae1e4bd281ada8cdf3ce13da](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/144978280/5b522782-68ee-4b9a-9ffd-49bace14ae81)
![60d1fd2edbd22ada0d84e2a45364414](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/144978280/3515744b-0d1c-4de6-aaa5-096acbd46706)
![174fd8352a7e81d82f4e0bdc2143b1a](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/144978280/8eabff36-9299-4d59-b730-d5f7e827e0df)

**Comment by adamgallas** [comment]
不好意思 不太想动脑了 2年前的工作了细节很多都不记得了

**Comment by 1218liu** [comment]
请问一下看到您的FCS.bin文件中是有三个标签的，复现您代码的时候检测口罩也是只出现过前两个标签，请问一下您的第三个标签是什么意思？你的这个第三个标签有出现过吗？因为我主要就是把您F开头的bin文件换成了我的，然后加了个我的FCS.bin文件，出现不了第三个标签我怀疑是不是您的这个代码只能检测到两个种类，想问一下您当时没有检测到过您的FCS.bin文件中第三个标签（incorr）？
![DWFRZ38$ R3B$)VD9H }V)P](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/144978280/bfd1da8a-3f83-40aa-a2f3-2f3d45ed9765)

**Comment by adamgallas** [comment]
有的，可以检测多个种类的，但是我忘了要改啥了。我之前也曾经完整地跑过yolo里面所有的类别的，只不过后面改成了只有两三个类的口罩识别。事实上这个yolo分类头和加速器无关，是在ps端完成的，你只需要改ps端的代码就行了
