### ISSUE TITLE
ifm及ofm尺寸最低256字节的问题

### ISSUE THREAD

**Issue by lllkjh** [adamgallas/fpga_accelerator_yolov3tiny#29]
大佬，又来打扰了。在C代码的Set_Next_OFM_ADDR_LEN()和Set_Next_IFM_ADDR_LEN()两个函数里，都有针对特征图尺寸小于256时按最低256处理的逻辑，想请教下这个是有什么用意呢？谢谢

![image](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/29267042/c18140ec-3f3f-4946-b451-e2a9d728ad08)

![image](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/29267042/ff716a06-8be0-4444-9cea-fdf7f783b10f)

**Comment by adamgallas** [comment]
是因为我设定了特征图的尺寸最小粒度为256，大于256的话，不同通道batch的特征图可以连续存储，小于256的话，我当时怕地址对齐的问题，就让一个通道batch的特征图和256对齐。但后面证明其实问题不大。。这个不是特别重要。
