### ISSUE TITLE
显示器没有显示，串口打印如下报错信息

### ISSUE THREAD

**Issue by DragMou1204** [adamgallas/fpga_accelerator_yolov3tiny#30]
![image](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/119485272/9f8cc01f-080c-419e-9ef1-88f5c0ab7daf)
，请问如何解决

**Comment by adamgallas** [comment]
视频采集-显示环路没有跑通。。移植没做好

**Comment by DragMou1204** [comment]
请问你是用原厂minidp转hdmi的线吗，上述训练失败问题已解决，但是显示器没有显示
