### ISSUE TITLE
自定义模型更改问题

### ISSUE THREAD

**Issue by thomasjeff0420** [adamgallas/fpga_accelerator_yolov3tiny#31]
您好，我目前正在进行一个有关面部识别的项目，我已经使用 yolov4 tiny 训练了一个自定义模型。 请让我知道我需要在哪里导入我的模型以及我需要在这个 git 项目中进行哪些更改。 谢谢。

**Comment by adamgallas** [comment]
抱歉，这个工程不是通用的加速器，和我用的简化版的yolov3tiny强耦合。建议你用vitis ai。

**Comment by 1218liu** [comment]
> 您好，我目前正在进行一个有关面部识别的项目，我已经使用 yolov4 tiny 训练了一个自定义模型。 请让我知道我需要在哪里导入我的模型以及我需要在这个 git 项目中进行哪些更改。 谢谢。
您好我目前想将源码的yolov3-tiny算法换成yolov5，可是我用yolov3tiny_quant.py文件来量化v5的权重文件时遇到了一些问题，请问您的yolov4 tiny跑量化操作的时候是修改了作者的yolov3tiny_quant.py文件还是说您用的是其他量化文件呢？能解答一下嘛，能冒昧的加你下您的联系方式嘛？

**Comment by adamgallas** [comment]
我劝你放弃，这个加速器不支持yolov4和yolov5。去学习vitis ai吧
________________________________
发件人: 1218liu ***@***.***>
发送时间: 2023年12月21日 18:28
收件人: adamgallas/fpga_accelerator_yolov3tiny ***@***.***>
抄送: Jindong Li ***@***.***>; State change ***@***.***>
主题: Re: [adamgallas/fpga_accelerator_yolov3tiny] 自定义模型更改问题 (Issue #31)


您好，我目前正在进行一个有关面部识别的项目，我已经使用 yolov4 tiny 训练了一个自定义模型。 请让我知道我需要在哪里导入我的模型以及我需要在这个 git 项目中进行哪些更改。 谢谢。
您好我目前想将源码的yolov3-tiny算法换成yolov5，可是我用yolov3tiny_quant.py文件来量化v5的权重文件时遇到了一些问题，请问您的yolov4 tiny跑量化操作的时候是修改了作者的yolov3tiny_quant.py文件还是说您用的是其他量化文件呢？能解答一下嘛，能冒昧的加你下您的联系方式嘛？

―
