### ISSUE TITLE
dma有关软件配置

### ISSUE THREAD

**Issue by DragMou1204** [adamgallas/fpga_accelerator_yolov3tiny#33]
![image](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/119485272/bd2c6271-b5b8-4602-afc8-7d14933ffa0f)
我看到ruan'jia软件部分只有这部分对axi dma的配置，前两行是复位，后两行是启动，配置中断阈值，并没有看到对dma的使用代码，没有指定传输地址等，是我哪里没有理解到吗

**Comment by adamgallas** [comment]
这个仅仅是配置dma而已。发起传输的函数在accel.c里的前两个函数，send。。。recv。。。什么的

**Comment by DragMou1204** [comment]
好的
