### ISSUE TITLE
程序卡在wait_ap done

### ISSUE THREAD

**Issue by DragMou1204** [adamgallas/fpga_accelerator_yolov3tiny#34]
cpu接受不到来自卷积模块的中断，我已经对中断的配置进行了很多检测，应该不是中断配置问题，我使用了ila调试，vdma1有数据传回ddr，但是dma没有数据传给卷积模块，卷积模块的s axis也在整个过程中都没有触发，我的dma和卷积部分的代码没有修改，硬件模块设置也是一样的，请问你有什么意见吗

**Comment by adamgallas** [comment]
“dma没有数据传给卷积模块”，ps端发起传输了吗？

**Comment by DragMou1204** [comment]
dma的axi-lite线吗，ila观察到该线有信号，
![image](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/119485272/ca0e8e7e-c59e-492d-866a-ee5cf6486b50)
但dma连接卷积模块的MM2S没有数据传输

**Comment by DragMou1204** [comment]
dma连接cpu的MM2S与S2MM信号线都没有数据传输

**Comment by adamgallas** [comment]
不好意思我也不知道为什么了。。axi lite线看到信号，应该就说明ps端正确地给dma发送指令了，应该mm2s和s2mm就会有数据进来了。。。除非dma没配置成功，但如果你调了那个accel system setup的函数，应该就设置成功了。。剩下的我也不知道问题出在哪里了

**Comment by DragMou1204** [comment]
好吧，我在研究研究
