### ISSUE TITLE
作者您好，请问该系统的吞吐率和准确率如何确定。

### ISSUE THREAD

**Issue by zhangxianbin1999** [adamgallas/fpga_accelerator_yolov3tiny#35]

**Comment by adamgallas** [comment]
你好，理论上吞吐率等于freq*dsp_num*2，但是这个系统并不完善，ps端的调度做的不好，导致有很多时间在等ps端发指令，每次dma issue cmd的时候也需要等待，所以达不到理论的吞吐率。实际的吞吐率可能只有一半左右。至于准确率，我也没有去跑量化后的mAP，当时我做的时候也比较粗糙，量化后相比起yolov3tiny有了挺大的准确率损失，但我现在也无法给一个准确的数字了
