### ISSUE TITLE
输出问题

### ISSUE THREAD

**Issue by look121212** [adamgallas/fpga_accelerator_yolov3tiny#42]
![b28e979e57d34ba15dfc1c89b559a05](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/105287188/27f1cc05-aa2a-40d5-894e-17cb1333df36)
这是我的输出情况，不太理解是什么原因导致的，我的版本是2023的。

**Comment by adamgallas** [comment]
这就是摄像头驱动没写好。你这个是vga显示器吧？看起来是你自己的vga驱动？还是你自己买了dp转vga转接头。摄像头采集和显示的回路得你们自己去调了

**Comment by look121212** [comment]
如果我直接用minidp转dp1.2的线，在dp显示器上输出是没问题的吗？

**Comment by look121212** [comment]
是买的转接头

**Comment by look121212** [comment]
请问你的显示器是什么？转接头用的什么？

**Comment by look121212** [comment]
![f5fb023e418f590c0339d83f27fdc6b](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/105287188/3a63855f-30fd-4c92-a054-2cd1eafecd04)
输出搞定了，但是用你SD文件夹里面的文件，SD启动，似乎识别不了？按过了BTN1，试过了蓝色和黑色口罩都不行

**Comment by look121212** [comment]
左上角出现aaaaa的字符

**Comment by look121212** [comment]
串口工具并没有任何输出

**Comment by adamgallas** [comment]
sd卡的权重必须得成功加载才行，串口正常会有输出的

**Comment by look121212** [comment]
好的，已经解决了，谢谢
