### ISSUE TITLE
我想从sd卡中读取图片进行检测，请问我该怎么做

### ISSUE THREAD

**Issue by DragMou1204** [adamgallas/fpga_accelerator_yolov3tiny#43]
我修改了load_pic（）的输入图片，并且取消了注释，关闭了摄像头的使能，但是屏幕还是不显示，串口输出检测的信息如下

**Comment by adamgallas** [comment]
没有摄像头就没有视频流进入vdma，屏幕不会显示的。串口输出你没有贴出来。魔改的步骤有很多，超出了我用爱发电的范围。。祝你好运吧

**Comment by DragMou1204** [comment]
能问一下这个吞吐量是怎么计算的吗



---- 回复的原邮件 ----
| 发件人 | Jindong ***@***.***> |
| 日期 | 2024年05月01日 11:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [adamgallas/fpga_accelerator_yolov3tiny] 我想从sd卡中读取图片进行检测，请问我该怎么做 (Issue #43) |

Closed #43 as completed.

**Comment by YuHao-Chang** [comment]
@DragMou1204 請問您最後有成功從SD卡中讀取圖片進行檢測嗎

**Comment by DragMou1204** [comment]
有的，按原作者步骤做



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2026年01月16日 22:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [adamgallas/fpga_accelerator_yolov3tiny] 我想从sd卡中读取图片进行检测，请问我该怎么做 (Issue #43) |
YuHao-Chang left a comment (adamgallas/fpga_accelerator_yolov3tiny#43)

@DragMou1204 請問您最後有成功從SD卡中讀取圖片進行檢測嗎
