### ISSUE TITLE
程序卡在了YOLOV3_TINY函数中的Inference函数

### ISSUE THREAD

**Issue by NightWingbat** [adamgallas/fpga_accelerator_yolov3tiny#46]
在PS端进行调试时，发现程序卡住了。经过Debug，发现程序卡在了YOLOV3_TINY函数中的Inference函数，当通过AXI_Lite总线给卷积核发送指令时出现了问题，尝试用ILA观察下AXI_Lite总线上的信号，但观察下来好像并没有发送读写的指令与数据，想要询问下解决办法。
![973059406132dd2b4464f1ef685db10e](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/113972458/e3070a1a-93d1-4c28-97f3-08f4a44561a9)
![image](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/113972458/01a27309-d673-46d4-97c0-fd8a661b8bae)
![Uploading image.png…]()

**Comment by NightWingbat** [comment]
![6daa7176a2dc351eff05cdf7a546137f](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/113972458/f8c57a3b-ab1a-4888-b5b5-35a45bdca2da)

**Comment by adamgallas** [comment]
意思是ps端往pl端写寄存器的时候ila并没有观测到对应的axi lite总线有活动？只能怀疑地址空间没有分配对了。你得手动改一下ACCEL_CTRL_ADDR的定义，改成vivado address map里面的地址。

**Comment by NightWingbat** [comment]
我之前检查过地址空间的问题。ACCEL_CTRL_ADDR的定义与PL端的地址空间是一致的。
![image](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/113972458/d8bfa800-9ddc-4a3c-a7c9-4c7df37726bd)
![image](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/113972458/8d049a8e-d8f1-4df6-bcd4-75b003a38613)
![ac1ff2bcecf77acacf1935b88e53a2fe](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/113972458/867d829b-fb07-406c-a60e-a7ed1ee4277f)

**Comment by adamgallas** [comment]
我也不知道为什么了。这里应该和加速器无关，ps端发起的写命令，axi_lite_waddr_valid肯定会拉高的。或者你的ila触发条件没弄对？
