### ISSUE TITLE
how to find config_list

### ISSUE THREAD

**Issue by Zhangyonglong** [adamgallas/fpga_accelerator_yolov3tiny#5]
hello, I am learning your sdk code now , but it is confused that the config_list has no definded. I hope can contact with you ,thank you !

**Comment by Zhangyonglong** [comment]
my e-mail is 1277520840@qq.com

**Comment by adamgallas** [comment]
config_list is defined in accel_data.c, and declared as an extern val in accel_data.h

**Comment by Zhangyonglong** [comment]
hi, I have found it in the bin file at sd card, thank you for your reply!
