### ISSUE TITLE
关于加速器性能GOP/s计算

### ISSUE THREAD

**Issue by PRJ614** [adamgallas/fpga_accelerator_yolov3tiny#50]
想问下作者，您这个峰值和平均分别是怎么计算的呀
![image](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/20488254/c95c9e47-ae34-4843-938e-6b5ea1102f0a)
 

我是这样算的：
![image](https://github.com/adamgallas/fpga_accelerator_yolov3tiny/assets/20488254/d55d3c9f-9a02-438e-8916-60faec471b4b)
2是一次乘法和一次加法，64*9是64个3x3卷积，按照我这样算最后是288GOPs（频率取250Mhz），

还有平均是怎么算的呀

**Comment by adamgallas** [comment]
你算的是对的，确实是288GOPs，那时候的我比较菜，不太会算。
平均是我通过计算yolov3tiny的总的运算量和的实际的推理延时计算出来的，可见其实这个加速器设计的还是有点问题，导致实际上GOPs利用率只有一半左右
