### ISSUE TITLE
cal_mult_int8_x2模块中的的算法问题

### ISSUE THREAD

**Issue by YangJinPiXiu** [adamgallas/fpga_accelerator_yolov3tiny#51]
在ac_comp=(bc_tmp[15]==1'b1)?(ac_tmp+1'b1):ac_tmp;中 bc_tmp<0时，ac_comp确实等于ac_tmp+1'b1，但是我不太明白这个算法的原理，可以给我解答一下吗

**Comment by adamgallas** [comment]
这个是在做int8 packing的error correction，详情可以看看xilinx的白皮书wp487-8-bit-acceleration

**Comment by YangJinPiXiu** [comment]
多谢解答    https://www.xilinx.com/support/documentation/white_papers/wp487-int8-acceleration.pdf
