### ISSUE TITLE
量化资料

### ISSUE THREAD

**Issue by xiaohuozi0** [adamgallas/fpga_accelerator_yolov3tiny#52]
请问有关于VGG16量化资料推荐吗，想把量化的参数导出，但没找到可靠的资料

**Comment by adamgallas** [comment]
量化的相关资料多的去了，博客也好论文也好，https://zhuanlan.zhihu.com/p/149659607。torch的量化教程也多的去了，https://pytorch.org/docs/stable/quantization.html，甚至都可以直接下载量化后的模型，https://pytorch.org/vision/stable/models.html。耐心学一学
