### ISSUE TITLE
请问特征图分段策略和加速器内部的读取中的地址偏移应该怎么理解

### ISSUE THREAD

**Issue by WHUDYF** [adamgallas/fpga_accelerator_yolov3tiny#53]
这是我之前学习硬件加速器部分画的一个图，我记得最后输出的特征图是蓝色的框和里面的黑色框的交集
![test_photo](https://github.com/user-attachments/assets/ed2090a5-db7a-4e34-a0ee-83bd8d85ca91)
这里是用ifm端的图像分割策略的代码举的一个例子
![yoloquestion](https://github.com/user-attachments/assets/b485aae2-b90e-44a8-a90e-8fd32bff7130)
还想问一下大佬，我刚开始学这部分，我发现accel_data.h文件里面有很多extern信号例如ap_done，但是我不知道为什么单单用一个extern就能把数据从pl端传到处理器里面处理了，我也没有在处理器文件内部发现有相关的代码，大佬可以解释一下吗？谢谢!
![yoloquestion2](https://github.com/user-attachments/assets/b07bd2c1-7963-403f-ad90-0bafec116c08)

**Comment by adamgallas** [comment]
图像分段的ps和pl端的代码确实晦涩难懂。不过我觉得你应该明白计算这些地址的offset之类的目的是什么，目的是考虑padding的情况下，选择正确的图像的行的起始地址。比如说一张完整的图像从上往下切成3份，第一份经过pl端运算后的第一行图像要保留，最后一行要舍弃，第二份图像的第一行和最后一行都要舍弃，第三份图像第一行要舍弃，最后一行要保留。这些复杂的逻辑，是为了切分后的图像在地址上最后还能拼在一块，形成一张完整的特征图。

第二个问题，.h头文件里面所有的extern变量全都可以在.c文件里面找到定义，这是c语言多文件项目共享一些全局变量的一种方法，这些变量都能在文件中找到引用和赋值的。
