### ISSUE TITLE
是否有相关的论文成果

### ISSUE THREAD

**Issue by wmdscjhdpy** [adamgallas/fpga_accelerator_yolov3tiny#6]
我的论文中参考了本项目的工作，想问一下作者在本项目中的工作是否有已发表的论文，我希望可以引用您的工作成果。

**Comment by adamgallas** [comment]
有的，不过只是一篇挺水的[ei检索论文](https://ieeexplore.ieee.org/abstract/document/9661886/), 感谢引用！

**Comment by wmdscjhdpy** [comment]
OK，感谢提供的信息和开源代码！个人建议可以把论文的bibtex引用和开源协议加到工程里
