### ISSUE TITLE
可否提供项目中的测试数据

### ISSUE THREAD

**Issue by wmdscjhdpy** [adamgallas/fpga_accelerator_yolov3tiny#7]
我正在试图将该项目的软硬件移植到RISC-V软核上，软件运行一切正常，但加速器总是给出显然错误的结果。我希望能够对比神经网络的中间数据，以找出我的系统中哪个环节存在问题，但项目中除了生成量化文件外没有任何关于加速器的仿真的testbench或matlab代码来对比。如果您在工作时有相关代码，可否附加在该项目中？这将给调试带来很大的帮助。

**Comment by adamgallas** [comment]
我能理解你遇到的问题。由于工程本身也很大，写testbench的工程量甚至超过了写这个加速器本身，当时我验证的时候就是反复上板+ila抓数据来完成验证的。
但是该工程是两年前完成的了，当时习惯不太好，测试的工程过于凌乱，也没有很好地维护，所以这个repo目前只具备参考价值了。只能你祝好运了
