### ISSUE TITLE
python工程无法复现

### ISSUE THREAD

**Issue by androny1012** [adamgallas/fpga_accelerator_yolov3tiny#9]
您好，facemask.yaml和yolov3-tiny-facemask.yaml在Readme中提到但没有提供

**Comment by adamgallas** [comment]
可能具体的需要要自己改一改
________________________________
发件人: androny1012 ***@***.***>
发送时间: 2023年3月24日 9:55
收件人: adamgallas/fpga_accelerator_yolov3tiny ***@***.***>
抄送: Subscribed ***@***.***>
主题: [adamgallas/fpga_accelerator_yolov3tiny] python工程无法复现 (Issue #9)


您好，facemask.yaml和yolov3-tiny-facemask.yaml在Readme中提到但没有提供

―

**Comment by adamgallas** [comment]
上传到python_prj/data里了
